import FooterTabs from "@/components/FooterTabs";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Paper from "@mui/material/Paper";

const inter = Inter({ subsets: ["latin"] });

import { cookies } from "next/headers";
import { genRandonString } from "@/utils/crypto";
import { Container } from "@mui/material";

export const metadata: Metadata = {
  title: "Create Next App1",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const gameId = cookies().get("gameId")?.value;
  console.log("sex", gameId);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Container component="main" maxWidth="sm" sx={{ mb: 4 }}>
          {children}
          <Paper sx={{ position: "fixed", bottom: 0, left: 0, right: 0 }} elevation={3}>
            <FooterTabs gameId={gameId} />
          </Paper>
        </Container>
      </body>
    </html>
  );
}
